version: "3.9"

name: stream-relay
services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: nginx-rtmp
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-rtmp-html/stat.xsl:/usr/local/nginx/html/stat.xsl:ro
    networks: [ relay-net ]

  ffmpeg-runner:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    container_name: ffmpeg-runner
    restart: unless-stopped
    entrypoint: [ "sleep", "infinity" ]
    volumes:
      - ./ffmpeg:/ffmpeg:ro
    networks: [ relay-net ]

  ffmpeg-loop:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    container_name: ffmpeg-loop
    restart: unless-stopped
    depends_on: [ nginx-rtmp ]
    command: >
      -re -stream_loop -1 -i /ffmpeg/brb.mp4
      -c copy -f flv rtmp://nginx-rtmp:1935/live/brb
    networks: [ relay-net ]
    volumes:
      - ./ffmpeg:/ffmpeg:ro

  auth-server:
    build: ./auth-server
    container_name: auth-server
    restart: unless-stopped
    environment:
      - TWITCH_STREAM_KEY=${TWITCH_STREAM_KEY}
    depends_on: [ nginx-rtmp, ffmpeg-runner ]
    networks: [ relay-net ]
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  panel-server:
    build: ./panel-server
    container_name: panel-server
    restart: unless-stopped
    environment:
      - TWITCH_STREAM_KEY=${TWITCH_STREAM_KEY}
      - YOUTUBE_STREAM_KEY=${YOUTUBE_STREAM_KEY}
    depends_on: [ nginx-rtmp ]
    networks: [ relay-net ]
    ports:
      - "4000:4000"
    volumes:
      - ./panel-server/public:/app/public:ro
      - /var/run/docker.sock:/var/run/docker.sock

  stream-guard:
    build: ./stream-guard
    container_name: stream-guard
    restart: unless-stopped
    depends_on: [ ffmpeg-runner, ffmpeg-loop ]
    networks: [ relay-net ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  relay-net:
    driver: bridge
